### ISSUE TITLE
css modules @value #{$sass-variable} is being broken by postcss-csso

### ISSUE THREAD

**Issue by v-trof** [lahmatiy/postcss-csso#10] opened 2017-08-04 14:24 UTC
See https://github.com/VsevolodTrofimov/csso-modules-bug
For reproduction

**Comment by lahmatiy** [comment] 2017-08-05 22:30
CSSO process a CSS, not a Saas or whatever. So issue isn't related to CSSO or Saas.
As I know css-modules exposes class names and id only (keyframes or smth like that also maybe, but not sure). Saas variables shouldn't to be exposed, but may be because of saas-loader.
I don't know how your pipeline works in details and where is the problem. Believe it isn't because of CSSO. Plugin may be, but there is to low chance for it. Are you sure it's because of postcss-csso and Saas var should be exposed?

**Comment by VsevolodTrofimov** [comment] 2017-08-05 22:38
This is why I create this issue in postcss-csso and not csso itself.
For some reason presence of exactly `postcss-csso` causes the issue

**Comment by VsevolodTrofimov** [comment] 2017-08-05 22:40
Btw, postcss gets css files Before they are being passed to css loader => `postcss-csso` cuts this from css itself

**Comment by VsevolodTrofimov** [comment] 2017-08-05 22:43
Yep, replicated without sass
`@value #{}` is being wiped.

**Comment by lahmatiy** [comment] 2021-04-05 21:53
Looks like the issue is related to #19 and fixed in [5.0.1](https://github.com/lahmatiy/postcss-csso/releases/tag/v5.0.1)

**Closed by lahmatiy** 2021-04-05 21:53 UTC
